version: '3.8'
name: cloud_project

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-projeto}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-projeto}
      POSTGRES_DB: ${POSTGRES_DB:-projeto}
    ports:
      - "5432:5432"

  app:
    image: davidconselvan/projeto-cloud:latest
    environment:
      SECRET_KEY: ${SECRET_KEY:-da39a3ee5e6b4b0d3255bfef95601890afd80709}
      DATABASE_URL: ${DATABASE_URL:-postgresql://projeto:projeto@db:5432/projeto}
      RAPIDAPI_KEY: ${RAPIDAPI_KEY:-9dc0cd25c5msh7093cea7eab33dbp1ed6d1jsne0b3a44acc73}
    ports:
      - "8000:8000"
    depends_on:
      - db
