site_name: API RESTful Cloud
site_description: Aplicação de web scraping que extrai dados de fontes específicas e os disponibiliza por meio de uma API RESTful construída com FastAPI e PostgreSQL. Utiliza uma arquitetura baseada em contêineres para portabilidade e facilidade de implantação, com imagens hospedadas no Docker Hub.
nav:
  - Home: index.md
  - Docker : docker.md
  - AWS : aws.md

site_url: https://DavidConselvan.github.io/API-RESTful-CLOUD/
theme:
  name: material
  highlightjs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.extra
  - pymdownx.details
  - pymdownx.superfences
  